@url = http://localhost:3001

### GET ToDo List
GET {{url}}/todo/list
Content-Type: application/json

### Add ToDo to List
POST {{url}}/todo/add
Content-Type: application/json

{
    "todo": "test2"
}

### Delete ToDo from List
DELETE {{url}}/todo/delete/33
Content-Type: application/json

### Update Todo from List
PUT {{url}}/todo/edit/9
Content-Type: application/json

{
    "todo": "test"
}

### Edit ToDo status
PUT {{url}}/todo/update/9
Content-Type: application/json