version: '3.8'

services:
  app:
    container_name: okr_app
    build: .
    image: okr_app
    ports:
      - "3001:3001"
    environment:
      - PG_DB=okr
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=db
    volumes:
      - ./:/home/node/app
      - ./App/models:/home/node/app/models
    depends_on:
      - db
    command: npm run dev
    restart: always
  db:
    container_name: okr_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=okr
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - node_db_data:/Library/PostgreSQL/15/data

volumes:
  node_db_data: {}